spring:
  datasource:
    url: jdbc:mysql://localhost:3306/house_agent?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties:
      hibernate:
        format_sql: true
server:
  port: 9000
